name: Build and publish

on:
  push:
    tags: [ "*" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Must start from tag
      if: github.ref_type != 'tag'
      run: |
        echo "Not a tag. Failing!"
        exit 1

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install system dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: |
          libc6-dev \
          libgl1-mesa-dev \
          libxcursor-dev \
          libxi-dev \
          libxinerama-dev \
          libxrandr-dev \
          libxxf86vm-dev \
          libasound2-dev \
          pkg-config
        version: 1.0

    # - name: Cache Go modules
    #   uses: actions/cache@v4
    #   with:
    #     path: |
    #       ~/.cache/go-build
    #       ~/go/pkg/mod
    #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    #     restore-keys: |
    #       ${{ runner.os }}-go-

    - name: Build
      run: |
        GOOS=linux GOARCH=amd64 go build -o tradewinds .
        GOOS=windows GOARCH=amd64 go build -o tradewinds.exe .

    - name: Changelog
      id: changelog
      env:
        v: ${{ github.ref_name }}
      run: |
        v=${v%%-*}
        changelog=$(sed -n '/^## \['$v'[]-]/,/^## \[/{/^## \['$v'/p;/^## \[/!p}' CHANGELOG.md | sed 's/^##/#/;/^EOF/d')
        echo "${changelog}"
        
        echo "version=${v}" >> $GITHUB_OUTPUT

        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo "${changelog}" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Publish release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ steps.changelog.outputs.version }}
        body: |
          ${{ steps.changelog.outputs.changelog }}
        draft: true
        files: |
          tradewinds
          tradewinds.exe
          LICENSE
        preserve_order: true
